paths:
  input_audio_dir: "/Users/hahea/Documents/Experiment_12/Analysis/Audio/Processed_recordings"
  output_root: "/Users/hahea/Documents/Experiment_12/Analysis/Audio/conversation_vad_labeler_package/outputs"

LANGUAGE: da
VAD_MIN_DURATION: 0.07
ENERGY_MARGIN_DB: 10.0
GAP_THRESH: 0.2
SHORT_UTT_THRESH: 0.7
MERGE_SHORT_AFTER_LONG: true
CACHE: true
ENTROPY_THRESHOLD: 1.5
